name: CI Frontend

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install frontend
        run: cd frontend && npm install
      
      - name: Build frontend
        run: cd frontend && npm run build
      
      - name: Type-check frontend
        run: cd frontend && npm run type-check